# Generated by Django 3.2.3 on 2021-05-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_auto_20210527_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='avliable',
            field=models.BooleanField(default=True),
        ),
    ]
